# Generated by Django 3.2.9 on 2021-11-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_auto_20211130_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='patform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplatform'),
        ),
    ]
